name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "super-dodgeball-royale"
          heroku_email: "ryan_henness@trimble.com"
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "super-dodgeball-royale-server"
          heroku_email: "ryan_henness@trimble.com"
